### ISSUE TITLE
[Bug] Broken Shop Permissions

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/StardustMC#11]
### Username

catter1

### Describe the issue

- Cannot rotate item frames
- Can claim when not supposed to

### Additional context

To others: add on stuff with permissions to do actions in your shop **plot** here instead of creating a new issue. Stuff involving chest shops and other things not *directly* realted should have their own issue.

**Comment by aisukuma** [comment]
- [x] Cannot rotate item frames
- [ ] Can claim in the shopping district when the player is not supposed to

**Comment by aisukuma** [comment]
Will be switching over to GriefDefender’s version of AdvancedRegionMarket, should fix both issues and other issues as well.
