### ISSUE TITLE
[Bug] Placing Wool Triggers Sculk Sensors

### ISSUE THREAD

**Issue by CodingPanda0623** [Stardust-Labs-MC/StardustMC#22]
### Username

PandaCalvin23

### Describe the issue

Sculk sensors are activated when wool is placed by the player. Although this doesn’t trigger shriekers and sculk sensor signals are still blocked by wool, it still is kinda annoying and unsettling while raiding an ancient city.

### Additional context

Probably need to test if the sensors triggered by wool can send redstone signals and such, and further testing regarding wool and sensor interactions.

**Comment by aisukuma** [comment]
Located the issue, one of the GM4 modules is causing it. Will look further into which module is causing it

**Comment by aisukuma** [comment]
Issue created on [GM4's Github repo](https://github.com/Gamemode4Dev/GM4_Datapacks/issues/895#issue-1864227768)

**Comment by aisukuma** [comment]
Issue has been fixed, will apply the update in the upcoming restart.
