### ISSUE TITLE
[Bug] Able to jump over Urbanyx area barrier

### ISSUE THREAD

**Issue by rowandevving** [Stardust-Labs-MC/StardustMC#23]
### Username

RowanDev

### Describe the issue

Using the Vibro shamir you are able to jump over the barrier that prevents you from accessing the new Urbanyx area.

**Comment by rowandevving** [comment]
Update: you are also able to pillar up from your own plot to do this

**Comment by aisukuma** [comment]
> Using the Vibro shamir you are able to jump over the barrier that prevents you from accessing the new Urbanyx area.

Hmm, I did not build the barrier high enough to consider that. I have the barrier setup to layout a foundation for the district upgrade.

> Update: you are also able to pillar up from your own plot to do this

WorldGuard issue, will see with catter what can be done
