### ISSUE TITLE
[Bug] Big pots dont show the shard 

### ISSUE THREAD

**Issue by skxlor** [Stardust-Labs-MC/StardustMC#25]
### Username

skxlor

### Describe the issue

Tried crafting one sided big pots with shards on one side. Me and my bedrock alt werent able to see the pattern. G-Glitch did see the pattern

**Comment by aisukuma** [comment]
Seems to be an issue with clients on 1.20+. The only solution for this is to update the server to 1.20.

**Comment by aisukuma** [comment]
Servers have been updated to 1.20.1, hopefully it should be fixed by now
