### ISSUE TITLE
[Bug] Experience Orbs no longer flying to player from long range

### ISSUE THREAD

**Issue by Cedric-Vii** [Stardust-Labs-MC/StardustMC#28]
### Username

Cedric_2

### Describe the issue

As in the title, Experience Orbs seem to be exhibiting Vanilla pickup behavior as of today, no longer flying to the player from range. Saku indicated it was working fine for them, so not sure if this is a single-client issue or a broader one. Have tested with both a Fabric and Vanilla install, both exhibiting vanilla behavior.

**Comment by aisukuma** [comment]
Fixed
