### ISSUE TITLE
[Bug] Iacio sometimes causes ender pearls to disappear?

### ISSUE THREAD

**Issue by CodingPanda0623** [Stardust-Labs-MC/StardustMC#31]
### Username

PandaCalvin23

### Describe the issue

I’ve noticed that pearling away while having the Iacio shamir on chestplate will occasionally play the “witch throws” sound (like it does when you normally pearl) and the pearl will just not land. This only happens if I pearl too far, it works fine if I pearl downwards.

**Comment by aisukuma** [comment]
This might be a plugin-datapack issue. In order to reproduce this, were you doing the following:
- Moving while tossing the ender pearl?
- Standing still while tossing the ender pearl?

**Comment by CodingPanda0623** [comment]
It happened multiple times, while I was standing still,  while I was jumping up, while I was sprinting forward, and while I was sprint jumping.

**Comment by aisukuma** [comment]
Located the issue, seems like a plugin that changes server simulation distance is not allowing ender pearls to properly land. Will be marking this as `unable to fix`, but I will increase the sim distance to 8, I just hope server performance doesn't tank
