### ISSUE TITLE
[Bug] Command Perms and auto completion 

### ISSUE THREAD

**Issue by ReiTheGoat01** [Stardust-Labs-MC/StardustMC#33]
### Username

Rei_the_Tipster

### Describe the issue

I noticed the /mail command does not auto complete but it does work

For Donators the /shakeitoff command does not auto complete and we don't have perms to use it
and while we have perms for /ride we don't have perms to ride anything if that makes sense. For example if I use /ride on a cow it will say You cant ride (cow) entity. The same goes for trying to ride players

**Comment by aisukuma** [comment]
Oh jeez, I need to individually set permissions for each entity for the ride command, fun.

As for the `/mail` command, permissions should be added for all players.

**Comment by aisukuma** [comment]
Fixed. `/shakeitoff` is now a command for default rank

Here are the mobs you can ride using the command:
- cow
- fox
- goat
- wolf
- panda
- polar bear
- sheep
- mushroom cow
- players

Will add this list to the wiki.
