### ISSUE TITLE
adminshop warp randomly selects to teleport you inside the shop or out the front of the pavilion

### ISSUE THREAD

**Issue by hannafoxie** [Stardust-Labs-MC/StardustMC#4]
### Username

abbifox

### Describe the issue

when using the /warp adminshop command i randomly go between being inside the adminshop and out the front of the entrance pavilion of the shop

**Comment by aisukuma** [comment]
Intended. Doing `/warp adminshop` again will take you to the front of the entrance as it is a second warp location.
