### ISSUE TITLE
Problem with item sorter hoppers or just hoppers in general

### ISSUE THREAD

**Issue by NotFalc0n** [Stardust-Labs-MC/StardustMC#43]
### Username

Notfalc0n

### Describe the issue

Using a slime block to push items along ice for a item sorter the items move to fast and wont go into the hoppers 

### Additional context

![image](https://github.com/Stardust-Labs-MC/StardustMC/assets/143766107/53c84220-182b-46eb-a747-b3a069d48088)
works in survival mode

**Comment by aisukuma** [comment]
I think I have fixed the problem, confirmed from latest server restart
