### ISSUE TITLE
[Bug] Zombified Piglins not aggroing on player

### ISSUE THREAD

**Issue by CodingPanda0623** [Stardust-Labs-MC/StardustMC#45]
### Username

PandaCalvin23

### Describe the issue

I've noticed that some zombified piglins don't get angry when others do and simply sit there confused until I hit them directly. In fact, angry ones literally run past them and they still just sit there. Not sure what may be causing the problem.

UPDATE: Apparently after a while, the farm completely stops and the zombified piglins stop being mad until they can make eye contact again. Temporary solution: constantly floating upwards with enderpuff causes all of them to aggro again.

![image](https://github.com/Stardust-Labs-MC/StardustMC/assets/91086673/38364231-d2da-472d-875f-b341adcc3121)

### Additional context

My gold farm relies on zombified piglins getting aggroed on me and getting entity crammed once they run to the killing chambers in the middle. There are 4 named zombified piglins on the corners of the farm to constantly give the others aggro. As seen in the photo above, only one piglin is aggroed and the rest of them are not. Making eye contact only causes most, not all, to aggro again as shown in the picture below.

![image](https://github.com/Stardust-Labs-MC/StardustMC/assets/91086673/850ef946-bba9-4c42-8090-151761a82945)

**Comment by aisukuma** [comment]
This issue is caused most likely from a plugin which changes simulation and view distance based on the server TPS.
