### ISSUE TITLE
[Bug] Shulker box invisibly stuck in the open position at lobby spawn

### ISSUE THREAD

**Issue by g-g-glitch** [Stardust-Labs-MC/StardustMC#52]
### Username

G_GLITCH

### Describe the issue

At the spawn area in the lobby, there's a shulker box invisibly stuck in the open position which blocks player movement.

### Additional context

Lobby shulker box at (675, 103, 678) is invisibly stuck open in the block above (675, 104, 678).

**Comment by aisukuma** [comment]
Fixed. I think.
