### ISSUE TITLE
[Bug] Wiki is not updated

### ISSUE THREAD

**Issue by Qsta981** [Stardust-Labs-MC/StardustMC#56]
### Username

Qsta981_

### Describe the issue

When I opened up the wiki, it was on season 2, not 2.5. The server now runs 1.20.4, but it still said 1.19.4, and it was not a typo because it specifically mentioned using the 1.20 experimental datapack.

### Additional context

It would be very helpful for people reading the wiki if they were not reading outdated info.

**Comment by aisukuma** [comment]
Many apologies, plenty of stuff has been reverted. 

Reason is here: https://discord.com/channels/738046951236567162/1002721350143721603/1245576962630619177
