### ISSUE TITLE
[Bug] It's 45 not 30 minutes downtime!

### ISSUE THREAD

**Issue by TheWiseDragon** [Stardust-Labs-MC/StardustMC#59]
### Username

TheWiseDragon

### Describe the issue

In the minecraft chat, it says "expect a 30-minute downtime" when the server is about to restart while on discord it's correct saying "expect a 45-minute downtime"

**Comment by aisukuma** [comment]
Fixed. Must have missed it when looking around and changing the message in the scheduler.
