### ISSUE TITLE
[Bug] Discord Live Chat is Inaccurate

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/StardustMC#8]
### Username

Flumpledorf

### Describe the issue

The server stats in [⁠live-chat](https://discord.com/channels/738046951236567162/1131733013693218926) display way less players than are online.

**Comment by catter1** [comment]
NTS: Attempt to remove the stats

**Comment by aisukuma** [comment]
Disabled topic, should be fixed I hope
