### ISSUE TITLE
[Bug] Bedrock Bugs

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/StardustMC#9]
### Username

catter1

### Describe the issue

- [Build on Nether Roof](https://github.com/Stardust-Labs-MC/StardustMC/discussions/7)
- Too many packets when using a boat
- [Geyser Offhand](https://discord.com/channels/738046951236567162/1137841023050068159/1142889274191122442)

### Additional context

Others, please add on to this issue instead of making a separate one.

**Comment by aisukuma** [comment]
- [x] ~~Build on Nether Roof~~ See stuff in the nether above y=128
- [x] Geyser Offhand
- [ ] ~~Too many packets when using a boat~~ Java players also have this issue

**Comment by aisukuma** [comment]
With Apollo's increased build height in the nether datapack, bedrock users can still *technically* build above the nether roof but won't be able to see anything above the nether roof with amplified nether active. [Might be related to this](https://github.com/GeyserMC/Geyser/issues/3804)
